#ifndef __IMPJS_ENUM_H__
#define __IMPJS_ENUM_H__

#include <dinput.h>

namespace stImpJSEnum {

enum INPUT {
	ST_DEVICE_OWN		= 30,
	ST_DEVICE_SHARE		= 31
};

enum JOY {
	ST_JS_X				= DIJOFS_X,
	ST_JS_Y				= DIJOFS_Y,
	ST_JS_Z				= DIJOFS_Z,
	
	ST_JS_RX			= DIJOFS_RX,
	ST_JS_RY			= DIJOFS_RY,
	ST_JS_RZ			= DIJOFS_RZ,
	
	ST_JS_BTN0			= DIJOFS_BUTTON0,
	ST_JS_BTN1			= DIJOFS_BUTTON1,
	ST_JS_BTN2			= DIJOFS_BUTTON2,
	ST_JS_BTN3			= DIJOFS_BUTTON3,
	ST_JS_BTN4			= DIJOFS_BUTTON4,
	ST_JS_BTN5			= DIJOFS_BUTTON5,
	ST_JS_BTN6			= DIJOFS_BUTTON6,
	ST_JS_BTN7			= DIJOFS_BUTTON7,
	ST_JS_BTN8			= DIJOFS_BUTTON8,
	ST_JS_BTN9			= DIJOFS_BUTTON9,
	ST_JS_BTN10			= DIJOFS_BUTTON10,
	ST_JS_BTN11			= DIJOFS_BUTTON11,
	ST_JS_BTN12			= DIJOFS_BUTTON12,
	ST_JS_BTN13			= DIJOFS_BUTTON13,
	ST_JS_BTN14			= DIJOFS_BUTTON14,
	ST_JS_BTN15			= DIJOFS_BUTTON15,
	ST_JS_BTN16			= DIJOFS_BUTTON16,
	ST_JS_BTN17			= DIJOFS_BUTTON17,
	ST_JS_BTN18			= DIJOFS_BUTTON18,
	ST_JS_BTN19			= DIJOFS_BUTTON19,
	ST_JS_BTN20			= DIJOFS_BUTTON20,
	ST_JS_BTN21			= DIJOFS_BUTTON21,
	ST_JS_BTN22			= DIJOFS_BUTTON22,
	ST_JS_BTN23			= DIJOFS_BUTTON23,
	ST_JS_BTN24			= DIJOFS_BUTTON24,
	ST_JS_BTN25			= DIJOFS_BUTTON25,
	ST_JS_BTN26			= DIJOFS_BUTTON26,
	ST_JS_BTN27			= DIJOFS_BUTTON27,
	ST_JS_BTN28			= DIJOFS_BUTTON28,
	ST_JS_BTN29			= DIJOFS_BUTTON29,
	ST_JS_BTN30			= DIJOFS_BUTTON30,
	ST_JS_BTN31			= DIJOFS_BUTTON31,
};

}

#endif /* !__IMPJS_ENUM_H__ */
